version: '3.9'
services:
  backend:
    build:
      context: ../backend
    container_name: zeiterfassung-backend
    ports:
      - "8082:8082"
    volumes:
      - backend_db:/app/db
    environment:
      - JAVA_OPTS=
  frontend:
    build:
      context: ../frontend
    container_name: zeiterfassung-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
volumes:
  backend_db:
    driver: local
